spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: 123456
  #session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #redsi配置
  redis:
    port: 6379
    host: localhost
    database: 1   #这里选择了redis的第1号数据库（默认是0号数据库所以查看数据库的时候要看一号）
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #设置cookie的作用域

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #将mybatis-plus默认自动将数据库的字段转换为驼峰：关闭设置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
